version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DEBUG=${BACKEND_DEBUG:-False}
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - API_URL=${API_URL:-http://backend:8000}
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
