#!/bin/bash

echo "🔧 Google OAuth Configuration Fix"
echo "================================="
echo ""
echo "The authentication error has been identified!"
echo ""
echo "❌ PROBLEM:"
echo "Your Google OAuth client is configured for different origins than what you're using."
echo ""
echo "✅ SOLUTION:"
echo "You need to add the correct origins to your Google OAuth client configuration."
echo ""
echo "🔗 Follow these steps:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. Navigate to: APIs & Services > Credentials"
echo ""
echo "3. Find your OAuth 2.0 Client ID:"
echo "   847322051930-4ae2t51qkjophm3lmgqvllg53vbh6bao.apps.googleusercontent.com"
echo ""
echo "4. Click Edit (pencil icon)"
echo ""
echo "5. In 'Authorized JavaScript origins', make sure you have:"
echo "   ✓ http://localhost:8000"
echo "   ✓ http://localhost:8080  (add this one)"
echo "   ✓ http://127.0.0.1:8000"
echo "   ✓ http://127.0.0.1:8080  (add this one)"
echo ""
echo "6. In 'Authorized redirect URIs', add if not present:"
echo "   ✓ http://localhost:8000"
echo "   ✓ http://localhost:8080"
echo ""
echo "7. Click 'Save'"
echo ""
echo "8. Wait 5-10 minutes for changes to propagate"
echo ""
echo "🚀 IMMEDIATE WORKAROUND:"
echo "Your frontend is now running on port 8000 (which should already be configured)"
echo "Try accessing: http://localhost:8000"
echo ""
echo "💡 TIP:"
echo "After updating Google OAuth, you can run on any port you prefer."
echo ""

# Check current server status
echo "📊 Current Server Status:"
if pgrep -f "python3 -m http.server 8000" > /dev/null; then
    echo "✅ Frontend server is running on port 8000"
    echo "   Access at: http://localhost:8000"
else
    echo "❌ Frontend server is not running on port 8000"
    echo "   To start: cd frontend && python3 -m http.server 8000"
fi

if pgrep -f "uvicorn app:app" > /dev/null; then
    echo "✅ Backend server is running"
else
    echo "❌ Backend server is not running"
    echo "   To start: cd backend && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
fi

echo ""
echo "🧪 Test the fix:"
echo "1. Open http://localhost:8000/debug-auth.html"
echo "2. Click 'Basic Auth Test'"
echo "3. If you see success, try the main app at http://localhost:8000"
echo ""
